### PR TITLE
fix: enable RNG bias correction

### LINKED ISSUE #85: `Rng` is not cryptographically secure
`Rng` implements `CryptoRng` without turning on the bias correction. This is a bad idea since its output is not guaranteed to be uniformly distributed without doing that.

### PR DESCRIPTION
**Pull request by chocol4te**
Closes #85.

### CODE REVIEW

File: nrf52-hal-common/src/rng.rs [hunk 1]
```diff
@@ -18,6 +18,7 @@ pub trait RngExt : Deref<Target=rng::RegisterBlock> + Sized {
 
 impl RngExt for RNG {
     fn constrain(self) -> Rng {
+        self.deref().config.write(|w| w.dercen().enabled());
```
Comment (jonas-schievink) [inline nrf52-hal-common/src/rng.rs]: `.deref()` should not need to be called manually

Comment (chocol4te) [reply nrf52-hal-common/src/rng.rs]: 🤦‍♂️ fixed
